[package]
name = "fuzz-introspector-client"
version = "0.0.1"
edition = "2021"
authors = ["Nathaniel Brough <nathaniel.brough@gmail.com>"]


[dependencies]
anyhow = "1.0.75"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.192", features = ["serde_derive"] }
serde_derive = "1.0.192"
serde_json = "1.0.108"
thiserror = "1.0.50"

[dev-dependencies]
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
clap = { version = "4.4.8", features = ["derive"] }

[[example]]
name = "introspector_query"
